# Generated by Django 6.0.5 on 2026-05-31 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("intake_seats", models.PositiveIntegerField()),
                ("established_year", models.PositiveSmallIntegerField()),
                ("location", models.CharField(max_length=255)),
                (
                    "college_type",
                    models.CharField(
                        choices=[("govt", "Government"), ("private", "Private")],
                        max_length=10,
                    ),
                ),
                ("is_ug", models.BooleanField(default=False)),
                ("is_pg", models.BooleanField(default=False)),
                ("has_mbbs", models.BooleanField(default=False)),
                ("has_dental", models.BooleanField(default=False)),
                ("has_nursing", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "colleges_college",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["college_type"], name="colleges_co_college_b33b1d_idx"
                    ),
                    models.Index(fields=["name"], name="colleges_co_name_4cf9c9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="colleges.college",
                    ),
                ),
            ],
            options={
                "db_table": "colleges_department",
                "unique_together": {("college", "name")},
            },
        ),
    ]
