# Generated by Django 5.0.6 on 2026-07-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_add_fee_stipend_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='college',
            name='google_maps_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='college',
            name='website_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
