# Generated by Django 5.0.6 on 2026-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_review_rejection_reason_review_resolved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('visible', 'Visible'), ('rejected', 'Rejected, resubmission allowed'), ('flagged', 'Flagged (pending review)'), ('removed', 'Removed by admin')], default='pending', max_length=10),
        ),
    ]
