# Generated by Django 5.0.6 on 2026-09-15 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_alter_review_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or advertisement'), ('offensive', 'Offensive or inappropriate'), ('misleading', 'Medically misleading / misinformation'), ('harassment', 'Harassment or bullying'), ('other', 'Other')], max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'colleges_answerreport',
            },
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or advertisement'), ('offensive', 'Offensive or inappropriate'), ('misleading', 'Medically misleading / misinformation'), ('harassment', 'Harassment or bullying'), ('other', 'Other')], max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'colleges_questionreport',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('visible', 'Visible'), ('flagged', 'Flagged (pending review)'), ('removed', 'Removed by admin')], default='visible', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('visible', 'Visible'), ('flagged', 'Flagged (pending review)'), ('removed', 'Removed by admin')], default='visible', max_length=10),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['status'], name='colleges_an_status_5c8cce_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status'], name='colleges_qu_status_9b04d5_idx'),
        ),
        migrations.AddField(
            model_name='answerreport',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='colleges.answer'),
        ),
        migrations.AddField(
            model_name='answerreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionreport',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='colleges.question'),
        ),
        migrations.AddField(
            model_name='questionreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='answerreport',
            unique_together={('answer', 'reporter')},
        ),
        migrations.AlterUniqueTogether(
            name='questionreport',
            unique_together={('question', 'reporter')},
        ),
    ]
