from django.urls import path
from .views import (
    CollegeListCreateView,
    CollegeDetailView,
    SeatEntryBulkUpdateView,
    FeeEntryBulkUpdateView,
    StipendEntryBulkUpdateView,
    CollegeBulkImportTemplateView,
    CollegeBulkImportView,
    CollegeReviewListCreateView,
    ReviewResubmitView,
    ReviewHelpfulView,
    ReviewReportView,
    ReviewPendingListView,
    ReviewAdminListView,
    ReviewHistoryListView,
    ReviewAdminActionView,
    MyReviewsView,
    TrendingReviewsView,
    RecentReviewsView,
    QuestionListCreateView,
    MyQuestionsView,
    QuestionDetailView,
    QuestionAnswerListCreateView,
    QuestionReportView,
    AnswerReportView,
    QuestionAdminListView,
    AnswerAdminListView,
    QuestionAdminActionView,
    AnswerAdminActionView,
)

urlpatterns = [
    path("",                              CollegeListCreateView.as_view(),         name="college-list-create"),
    path("<int:pk>/",                     CollegeDetailView.as_view(),             name="college-detail"),
    path("<int:pk>/seats/",              SeatEntryBulkUpdateView.as_view(),       name="college-seats"),
    path("<int:pk>/fees/",               FeeEntryBulkUpdateView.as_view(),        name="college-fees"),
    path("<int:pk>/stipends/",           StipendEntryBulkUpdateView.as_view(),    name="college-stipends"),
    path("<int:pk>/reviews/",            CollegeReviewListCreateView.as_view(),   name="college-reviews"),
    path("<int:pk>/questions/",          QuestionListCreateView.as_view(),        name="college-questions"),
    path("bulk-import/",                 CollegeBulkImportView.as_view(),         name="college-bulk-import"),
    path("bulk-import/template/",        CollegeBulkImportTemplateView.as_view(), name="college-bulk-import-template"),
    path("reviews/mine/",                 MyReviewsView.as_view(),                 name="reviews-mine"),
    path("reviews/trending/",            TrendingReviewsView.as_view(),           name="reviews-trending"),
    path("reviews/recent/",              RecentReviewsView.as_view(),             name="reviews-recent"),
    path("reviews/flagged/",             ReviewAdminListView.as_view(),           name="reviews-flagged"),
    path("reviews/pending/",             ReviewPendingListView.as_view(),         name="reviews-pending"),
    path("reviews/history/",             ReviewHistoryListView.as_view(),         name="reviews-history"),
    path("reviews/<int:pk>/helpful/",    ReviewHelpfulView.as_view(),             name="review-helpful"),
    path("reviews/<int:pk>/report/",     ReviewReportView.as_view(),              name="review-report"),
    path("reviews/<int:pk>/admin/",      ReviewAdminActionView.as_view(),         name="review-admin"),
    path("reviews/<int:pk>/resubmit/",   ReviewResubmitView.as_view(),            name="review-resubmit"),
    path("questions/mine/",              MyQuestionsView.as_view(),               name="questions-mine"),
    path("questions/flagged/",           QuestionAdminListView.as_view(),         name="questions-flagged"),
    path("answers/flagged/",             AnswerAdminListView.as_view(),           name="answers-flagged"),
    path("questions/<int:pk>/",          QuestionDetailView.as_view(),            name="question-detail"),
    path("questions/<int:pk>/answers/",  QuestionAnswerListCreateView.as_view(),  name="question-answers"),
    path("questions/<int:pk>/report/",   QuestionReportView.as_view(),            name="question-report"),
    path("questions/<int:pk>/admin/",    QuestionAdminActionView.as_view(),       name="question-admin"),
    path("answers/<int:pk>/report/",     AnswerReportView.as_view(),              name="answer-report"),
    path("answers/<int:pk>/admin/",      AnswerAdminActionView.as_view(),         name="answer-admin"),
]
