# Generated by Django 5.0.6 on 2026-08-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='batch',
            field=models.CharField(blank=True, default='', help_text='Batch year, e.g. 2016. Required when current_status is a student or alumni status.', max_length=20),
        ),
    ]
