# Generated by Django 5.0.6 on 2026-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pg_department',
            field=models.CharField(blank=True, choices=[('Anatomy', 'Anatomy'), ('Biochemistry', 'Biochemistry'), ('Physiology', 'Physiology'), ('Community Medicine (PSM)', 'Community Medicine (PSM)'), ('Forensic Medicine & Toxicology', 'Forensic Medicine & Toxicology'), ('Microbiology', 'Microbiology'), ('Pathology', 'Pathology'), ('Pharmacology', 'Pharmacology'), ('Anaesthesiology', 'Anaesthesiology'), ('Dermatology, Venereology & Leprosy (DVL)', 'Dermatology, Venereology & Leprosy (DVL)'), ('Emergency Medicine', 'Emergency Medicine'), ('General Medicine', 'General Medicine'), ('Paediatrics', 'Paediatrics'), ('Psychiatry', 'Psychiatry'), ('Radiology / Radiodiagnosis', 'Radiology / Radiodiagnosis'), ('Respiratory Medicine', 'Respiratory Medicine'), ('ENT (Otorhinolaryngology)', 'ENT (Otorhinolaryngology)'), ('General Surgery', 'General Surgery'), ('Obstetrics & Gynaecology', 'Obstetrics & Gynaecology'), ('Ophthalmology', 'Ophthalmology'), ('Orthopaedics', 'Orthopaedics'), ('Cardiology', 'Cardiology'), ('Critical Care Medicine', 'Critical Care Medicine'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('Medical Oncology', 'Medical Oncology'), ('Neonatology', 'Neonatology'), ('Nephrology', 'Nephrology'), ('Neurology', 'Neurology'), ('Rheumatology', 'Rheumatology'), ('Cardiovascular & Thoracic Surgery (CTVS)', 'Cardiovascular & Thoracic Surgery (CTVS)'), ('Neurosurgery', 'Neurosurgery'), ('Paediatric Surgery', 'Paediatric Surgery'), ('Plastic & Reconstructive Surgery', 'Plastic & Reconstructive Surgery'), ('Surgical Gastroenterology', 'Surgical Gastroenterology'), ('Surgical Oncology', 'Surgical Oncology'), ('Urology', 'Urology')], default='', help_text='Self-reported PG specialty — drives which Specialty Communities this profile is auto-joined to.', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_status',
            field=models.CharField(blank=True, choices=[('ug_aspirant', 'UG Aspirant'), ('ug_student', 'UG Student'), ('pg_aspirant', 'PG Aspirant'), ('pg_student', 'PG Student'), ('working_professional', 'Working Professional'), ('alumni', 'Alumni'), ('faculty', 'Faculty / Professor'), ('other', 'Other')], default='', max_length=30),
        ),
    ]
