# Generated by Django 5.0.6 on 2026-09-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_pg_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether this user has confirmed ownership of their email via the OTP verification flow.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=None, help_text='Public display name shown on Q&A and Discussions. Reviews stay anonymous. Alphanumeric and underscores only.', max_length=30, null=True, unique=True),
        ),
    ]
