# Generated by Django 5.0.6 on 2026-09-15 08:19

import django.db.models.deletion
import modules.accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_email_verified_alter_user_username'),
        ('colleges', '0009_alter_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pg_college_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ug_college_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CollegeChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('ug_college', 'UG College'), ('pg_college', 'PG College')], max_length=10)),
                ('proof', models.FileField(upload_to=modules.accounts.models.college_change_proof_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('current_college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='colleges.college')),
                ('requested_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='colleges.college')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_collegechangerequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
