# Generated by Django 5.0.6 on 2026-09-17 11:41

import django.core.validators
import modules.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_pg_college_set_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegechangerequest',
            name='proof',
            field=models.FileField(upload_to=modules.accounts.models.college_change_proof_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
