# Generated by Django 5.0.6 on 2026-09-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_collegechangerequest_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('final', 'Final Year'), ('internship', 'Internship')], default='', help_text="Which year of the course they're currently in — optional, only meaningful for ug_student/pg_student. Not the same as batch (admission year).", max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='batch',
            field=models.CharField(blank=True, default='', help_text="Batch/admission year, e.g. 2016. Required when current_status is a student or alumni status. Distinct from year_of_study (which year of the course they're currently in) — the two are not the same thing.", max_length=20),
        ),
    ]
