# Generated by Django 5.0.6 on 2026-09-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_year_of_study_alter_userprofile_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_reason',
            field=models.CharField(blank=True, default='', help_text="Super admin's note on why this account was blocked. Reference only — the blocked user can't log in to see it.", max_length=300),
        ),
    ]
