# Generated by Django 5.0.6 on 2026-10-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_blocked_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pg_batch',
            field=models.CharField(blank=True, default='', help_text="The PG year: admission year while still pursuing PG (pg_student), or completion year once PG is finished (working_professional/alumni/faculty with highest_education == pg). Blank for anyone who hasn't done PG.", max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='batch',
            field=models.CharField(blank=True, default='', help_text="The UG year: admission year while still pursuing UG (ug_student), or completion year once UG is finished (pg_aspirant/pg_student and any working_professional/alumni/faculty profile, regardless of highest_education — PG itself always requires having finished UG first). Distinct from year_of_study (which year of the course they're currently in).", max_length=20),
        ),
    ]
