# Generated by Django 5.0.6 on 2026-10-06 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_pg_batch_alter_userprofile_batch'),
        ('colleges', '0010_answerreport_questionreport_answer_report_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_profiles', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_college_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collegechangerequest',
            name='field',
            field=models.CharField(choices=[('ug_college', 'UG College'), ('pg_college', 'PG College'), ('work_college', 'Workplace College')], max_length=20),
        ),
    ]
