# Generated by Django 5.0.6 on 2026-09-11 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('national_overall', 'National — All PG Doctors'), ('department_national', 'Department — National'), ('department_state', 'Department — State')], max_length=20)),
                ('department', models.CharField(blank=True, choices=[('Anatomy', 'Anatomy'), ('Biochemistry', 'Biochemistry'), ('Physiology', 'Physiology'), ('Community Medicine (PSM)', 'Community Medicine (PSM)'), ('Forensic Medicine & Toxicology', 'Forensic Medicine & Toxicology'), ('Microbiology', 'Microbiology'), ('Pathology', 'Pathology'), ('Pharmacology', 'Pharmacology'), ('Anaesthesiology', 'Anaesthesiology'), ('Dermatology, Venereology & Leprosy (DVL)', 'Dermatology, Venereology & Leprosy (DVL)'), ('Emergency Medicine', 'Emergency Medicine'), ('General Medicine', 'General Medicine'), ('Paediatrics', 'Paediatrics'), ('Psychiatry', 'Psychiatry'), ('Radiology / Radiodiagnosis', 'Radiology / Radiodiagnosis'), ('Respiratory Medicine', 'Respiratory Medicine'), ('ENT (Otorhinolaryngology)', 'ENT (Otorhinolaryngology)'), ('General Surgery', 'General Surgery'), ('Obstetrics & Gynaecology', 'Obstetrics & Gynaecology'), ('Ophthalmology', 'Ophthalmology'), ('Orthopaedics', 'Orthopaedics'), ('Cardiology', 'Cardiology'), ('Critical Care Medicine', 'Critical Care Medicine'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('Medical Oncology', 'Medical Oncology'), ('Neonatology', 'Neonatology'), ('Nephrology', 'Nephrology'), ('Neurology', 'Neurology'), ('Rheumatology', 'Rheumatology'), ('Cardiovascular & Thoracic Surgery (CTVS)', 'Cardiovascular & Thoracic Surgery (CTVS)'), ('Neurosurgery', 'Neurosurgery'), ('Paediatric Surgery', 'Paediatric Surgery'), ('Plastic & Reconstructive Surgery', 'Plastic & Reconstructive Surgery'), ('Surgical Gastroenterology', 'Surgical Gastroenterology'), ('Surgical Oncology', 'Surgical Oncology'), ('Urology', 'Urology')], default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', help_text='Cached display name — computed on save if left blank.', max_length=180)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'communities',
                'db_table': 'communities_community',
                'indexes': [models.Index(fields=['type', 'department', 'state'], name='communities_type_e04c6a_idx')],
                'unique_together': {('type', 'department', 'state')},
            },
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('flagged', 'Flagged (pending review)'), ('removed', 'Removed by admin')], default='visible', max_length=10)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communities.community')),
            ],
            options={
                'db_table': 'communities_discussionpost',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('flagged', 'Flagged (pending review)'), ('removed', 'Removed by admin')], default='visible', max_length=10)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='communities.discussionpost')),
            ],
            options={
                'db_table': 'communities_communitycomment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionPostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or advertisement'), ('offensive', 'Offensive or inappropriate'), ('misleading', 'Medically misleading / misinformation'), ('harassment', 'Harassment of another member'), ('other', 'Other')], max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='communities.discussionpost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_discussionpostreport',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='communities.discussionpost')),
            ],
            options={
                'db_table': 'communities_polloption',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='communities.polloption')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='communities.discussionpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_pollvote',
            },
        ),
        migrations.CreateModel(
            name='CommunityCommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or advertisement'), ('offensive', 'Offensive or inappropriate'), ('misleading', 'Medically misleading / misinformation'), ('harassment', 'Harassment of another member'), ('other', 'Other')], max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='communities.communitycomment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_communitycommentreport',
                'unique_together': {('comment', 'reporter')},
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time this user opened this community — drives the unread badge.', null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communities_communitymembership',
                'indexes': [models.Index(fields=['user', 'is_active'], name='communities_user_id_eb609c_idx')],
                'unique_together': {('user', 'community')},
            },
        ),
        migrations.AddIndex(
            model_name='discussionpost',
            index=models.Index(fields=['community', 'status'], name='communities_communi_d84071_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionpost',
            index=models.Index(fields=['author'], name='communities_author__af0a6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discussionpostreport',
            unique_together={('post', 'reporter')},
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('post', 'user')},
        ),
    ]
