# Generated by Django 5.0.6 on 2026-09-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(choices=[('national_overall', 'National, All PG Doctors'), ('department_national', 'Department, National'), ('department_state', 'Department, State')], max_length=20),
        ),
    ]
