# Generated by Django 5.0.6 on 2026-09-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('review_new', 'New review at your college'), ('review_approved', 'Your review was approved'), ('review_rejected', 'Your review was rejected'), ('review_helpful', 'Someone found your review helpful'), ('answer_new', 'Someone answered your question'), ('question_new', 'New question at your college'), ('discussion_reply', "New reply in a discussion you're part of"), ('community_comment', 'New comment on your community post'), ('college_change_approved', 'Your college change request was approved'), ('college_change_rejected', 'Your college change request was rejected'), ('content_edited', 'Your content was edited by an admin')], max_length=30),
        ),
    ]
